spring:
  profiles: peer1
eureka:
  instance:    
    hostname: eureka-peer1    
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8762/eureka,http://eureka-peer1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8761

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8762/eureka,http://eureka-peer1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8762
